#!/bin/sh
#
# Copyright (C) 2017  Dridi Boukelmoune
# All rights reserved.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

. "${VCDK_SETUP}/vcdk-setup.sh"
. "${VCDK_PLUGIN_DIR}/autotools--codegen.sh"

OPTIONS_USAGE="\
Usage: vcdk autotools [--vmod <vmod> [--vsc <vsc>]] [--vut <vut>] <name>
       vcdk autotools --help

At least one VMOD or one VUT must be specified, a VSC can only be used
in a VMOD. The name of the project must match this extended regular
expression:

    $VCDK_NAME_REGEX

Options:
"

OPTIONS_SPEC="\
--output=<dir>		default: the project name
--pkg=<list>		only 'rpm' is supported
--scm=<scm>		only 'git' (default) is supported
--verbose		display additional information
--vmod=<list>		names of vmods to build
--vsc=<list>		names of counters to build
--vut=<list>		names of utilities to build
"

output=
pkg=
scm=
verbose=false
vmod=
vsc=
vut=

options_init "$@"
shift $opt_ind

test $# -gt 0 ||
usage_error 'missing project name'

test $# -eq 1 ||
usage_error 'too many arguments'

name=$1

test -n "$name" ||
usage_error 'missing project name'

echo "$name" |
grep -Eq "$VCDK_NAME_REGEX" ||
usage_error "invalid project name: $name"

test -n "$vmod" ||
test -n "$vut" ||
usage_error 'no VMOD and no VUT to build'

test -z "$vsc" ||
test -n "$vmod" ||
usage_error 'a VSC can only be used by a VMOD'

scm=${scm:-git}

case $scm in
	git) ;;
	*) usage_error "unknown scm: $scm" ;;
esac

output=${output:-$name}
rmdir "$output" 2>/dev/null || :
mkdir "$output"
cd "$output"

bootstrap >bootstrap
chmod +x bootstrap

configure_ac >configure.ac
makefile_am >Makefile.am

case $scm in
	git) _gitignore >.gitignore ;;
	*) ;; # unreachable
esac

mkdir src

src_makefile_am >src/Makefile.am

OLD_IFS=$IFS
IFS=,
for v in $vmod
do
	src_vmod_c $v >src/vmod_$v.c
	src_vmod_vcc $v >src/vmod_$v.vcc
done

for v in $vut
do
	src_vut_c $v >src/$v.c
	src_vut_options_h $v >src/${v}_options.h
	src_vut_rst_in $v >src/${v}.rst.in
done

mkdir src/vtc

for v in $vmod
do
	src_vtc_vmod_vtc $v >src/vtc/vmod_$v.vtc
done
IFS=$OLD_IFS

